version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  api-dev:
    build: 
      context: .
      target: builder
    ports:
      - "8001:8000" 
    volumes:
      - ./src:/app/src
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=8000